name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # ✅ Updated Firebase packages (compatible versions)
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  firebase_app_check: ^0.2.2+7
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  dart_openai: ^5.1.0
  email_validator: ^2.0.1
  flutter_tts: ^4.0.2
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
